[package]
name = "rtsq"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cc="*"

[dependencies]
tree-sitter = "0.20.0"
walkdir = "2.3.2"
clap = "2.33.3"